@startmindmap
* 活动规则
** 土地矿池开采
*** 规则
**** 分红池生成
***** 每日消耗的luck销毁，并按比例生成luck进入分红池
***** 每日消耗的usdt按照比例进入分红池
***** 每日按照算法生成lulu进入分红池
****** 算法待定
**** 分红池发放
***** 按照土地的创建时间区分，每天一个组，从昨天开始，\n昨天分红池50%，前天25%，依此类推
***** 每个组内按照权重分红
****** 权重规则待定
***** 某个组没人分红则该组不分红
*** lulu总共挖总数的5%\nluck总共挖总数的50%

** 庄园NFT质押挖矿
*** 规则未定

** 邀请挖矿
*** 给代理按照消费的luck和usdt数量分别按照一定比例返luck，分两级代理，比例不同
*** 代理获得的luck每满100个同时附赠一把lkey用于开宝箱

** 碎片获得
*** 内容
**** 物料碎片
**** 道具碎片
*** 获取方式
**** 耕種或開采的隨機掉落
**** 開寶箱獲得
**** 完成任務獲得
@endmindmap
