@startmindmap
* 货币
** 平台货币
*** LULU
**** 获得
***** market游戏挖矿
****** 土地矿池开采
***** 私募
**** 使用
***** 质押分红

*** LUCK
**** 获得
***** 去中心化交易所
***** 空投
***** 挖矿
****** 土地矿池开采
****** 庄园NFT质押挖矿
****** 邀请挖矿
**** 使用
***** 购买角色卡
****** 可以使用luck或者luck+usdt购买角色卡
***** 物料包
****** 购买物料包
****** 补足合成物料包不足的碎片
***** 道具
****** 购买道具
****** 补足合成道具不足的碎片
***** 土地升级

*** LUSD
**** 具体规则暂定
**** 获得
***** 土地挖矿分红
**** 使用
***** 未定

*** LKEY
**** 获得
***** 邀请挖矿
***** 空投
***** 去中心化交易所
**** 使用
***** 开宝箱

** 外部货币
*** USDT
**** 常规消费项目
*** BNB
**** 铸造庄园nft
**** 庄园nft拍卖
@endmindmap
