@startmindmap
* 农场游戏

** 开始游戏
*** 获取庄园信息
**** call
***** getLandList
***** getMarket
**** 开放的位置数据
***** LandSlot
**** 如何解锁新位置？
***** 自动/手动？条件
***** demo版本写死4个位置
**** 位置数据内容
***** 是否开放
***** 土地

** round
*** 订阅
*** 当前正在跑的指定用户的round
*** round数据内容
**** 开始时间
**** 用户
**** 位置
**** 土地
**** 物料
**** 状态
**** 刷新时间

** 土地放置
*** 获取土地列表
**** call
**** 可用的土地列表数据
***** 持有的可用nft数据
***** NonFungibleTokenItem
*** 放置土地
**** call(位置，土地)
***** bindLand
**** 绑定
***** 位置没有绑定土地
**** 更换
***** 位置绑定了土地
**** 解绑
***** 土地传入的参数为空
**** 正在执行round则不可以操作

** 开始耕种
*** 获取物料列表
**** call
***** getSeedList
**** 物料列表
***** Seed
**** 物料数据内容
***** 名称
***** 单价
***** 特性
***** 收获时间
*** 指定物料开始耕种
**** call(位置，物料，数量)
**** 正在执行round则不可以操作
**** 没有装配土地不可以操作

** 收获
*** call(位置)
**** 收成结果
@endmindmap
