
export default {
  serviceTerms: `
  Terms and Conditions

  December 22, 2021

  These Terms and Conditions constitute the User Agreement and Terms of Service (hereafter the “Terms & Conditions”) between BEECOINS DIGITAL LTD. (referred to as “LULU” or the “Site”) and any person, customer, or entity (referred as the “User”) utilizing the website, BEECOINS DIGITAL and any products, features and services provided thereon (“LULU Services”). These Terms & Conditions do not create any agency, partnership, or joint venture between LULU and User. By signing up for an account through LULU or any associated websites, APIs, or mobile applications, the User has read and consents to the Terms & Conditions. The User also agrees to LULU’s Privacy Policy and Code of Conduct. These Terms & Conditions may be amended and updated from time to time at the sole discretion of LULU. Revised versions will be considered effective as of the date and time posted on the LULU Site.

  1. LULU SERVICES.

  LULU is a decentralized distributed application on a blockchain network, using smart contracts (each a “Smart Contract”) to enable its Users to own, buy, sell, transfer, and share unique digital rewards that can be visualized on the LULU site through the LULU App.

  1.1 LULU Game Node. LULU Game Node is a computer software and hardware system connected to LULU. The LULU Game Node supports blockchain video games by maintaining the cryptography and confirming transactions on the LULU Blockchain through the LULU App. Used herein, “LULU Game Node” may represent either the node itself of a license the User obtains to run said node.  The LULU Game Nodes when combined form the “LULU Game Node Network”.

  1.2 LULU Blockchain. The LULU Blockchain allows each User to store items, characters, digital rewards, and other attributes on the LULU Blockchain public ledger that allows for decentralized, immutable record of ownership. Each User owns the non-fungible token (an “NFT”) for any of the in-game items on the LULU Blockchain. When a User purchases, earns, or receives any NFT or digital reward the Smart Contract process, the User owns completely and outright the NFT and/or digital reward.

  1.3 LULU Reward. Each User of any game on the LULU Blockchain or the Site or any game contained on the Site or associated websites, and associated LULU Game Node, may be able to earn or receive the LULU Reward. The “LULU Reward” consists of a representation of LULU token, or other game tokens and NFTs, reflected on the LULU Blockchain and/or LULU App and the Site, which may or may not be bridged to other blockchains (including but not limited to Ethereum) through a minting process solely at the option and action of the User.  When referencing the NFTs on the platform themselves in the singular and not specifically as a part of the LULU Reward, same shall be referred to herein as “Platform Asset.” The LULU Reward is a digital reward and not a Security Token.  The LULU Reward is not being offered to investors and there is no Initial Coin Offering (ICO) to promote the LULU Reward. Like BTC (which is the digital reward generated from the Bitcoin blockchain), the LULU reward is created through a unique blockchain protocol. Each User that participates in the LULU Blockchain protocol shall receive 100% of the User’s allocated LULU Reward and any other digital reward or NFT, which is deposited in the User’s LULU App. The LULU Reward, any NFT, and any other digital reward may reside solely within the LULU Blockchain, and may or may not have value.  LULU cannot, and does not, control whether any of the LULU Reward, any NFT, and any other digital reward has monetary value on any other blockchain.  On the LULU Blockchain, the Site, or any associated website, neither the LULU Reward nor NFT nor other digital reward may be exchanged for currency.

  1.5 LULU App

  1.5.1. LULU will provide each User with a LULU App. LULU will never take custody or control over any NFT or digital reward stored in a User’s LULU App. The LULU App does not store, send or receive any NFT or reward, but such transactions occur directly on the LULU Blockchain or other supported blockchains. Instead of the LULU App, the User may use any compatible digital app or wallet provided by a third party company that safely connects to the LULU Blockchain. A User may be able to use the LULU App or other compatible wallet to send and receive any NFT or digital reward with other users of the LULU Blockchain. LULU does not offer any User the ability to exchange one form of currency for any other form of currency (fiat or digital). LULU App is not a custodian, exchange or money transmitter.

  1.5.2. When a User creates a LULU App, the LULU Blockchain software generates a cryptographic private key and public key pair that the User must use to send and receive any NFT or digital reward supported on the LULU Blockchain. The User is solely responsible for storing, outside of LULU’s Services, a backup of any User’s LULU App, private key(s), or transaction information that the User maintains in the LULU App or otherwise with the LULU Services. If the User does not backup the LULU App, the User may not be able to access the LULU in the event that LULU discontinues some or all of the LULU Services.

  1.5.3. In order for a transaction to be validated on the LULU Blockchain, any LULU transaction through the LULU App must be confirmed and recorded in the distributed ledger associated with the LULU Blockchain. The LULU Blockchain is a decentralized, peer-to-peer network supported by the users of the LULU Blockchain, which is not owned, controlled or operated by LULU.

  1.5.4. LULU has no control over any NFT or digital reward (including the LULU Reward) generated through the LULU Blockchain or the LULU App or Site, and cannot ensure that any transaction details a User submits via the LULU Services and LULU App or Site will be confirmed or processed on the LULU Blockchain. The User agrees and understands that the transaction details submitted by the User via the LULU Services and LULU App may not be completed or may be delayed by the LULU Blockchain or any supporting blockchain used to process the transaction. LULU does not guarantee that the LULU App can transfer title or right in any NFT or digital reward, and LULU makes no warranties of title of any kind. Once transaction details have been submitted to the LULU Blockchain, LULU cannot assist the User to cancel or otherwise modify such transaction or details.

  1.5.5. In the event of a fork of the LULU Blockchain or any other supported blockchain, LULU may not be able to support the User’s activity related to LULU or any other supported NFT or reward. The User agrees and understands that in the event of a fork of the LULU Blockchain, any transaction associated with the LULU App or LULU Services may not be completed, may be partially completed, incorrectly completed, or substantially delayed. LULU is not responsible for any loss incurred by any User caused in whole or in part, directly or indirectly, by a fork of the LULU Blockchain.

  1.5.6. With respect to the LULU App, LULU does not receive or store a User’s LULU App password, or any keys, network addresses or transaction history. LULU cannot assist any User with LULU App password retrieval. The User is solely responsible for remembering, storing and keeping secret the User’s LULU App PIN (password), keys and address. Any NFT or digital reward a User has stored within its LULU App may become inaccessible if the User does not know or keep secret its LULU App keys and PIN. Any third party with knowledge of one or more of a User’s credentials (including, without limitation, a backup phrase, App identifier, PIN, or keys) can dispose of the NFT or digital rewards in the User’s LULU App.

  1.5.7. LULU does not currently charge a fee for the LULU App, receiving, sending, or storing LULU. However, LULU reserves the right to do so in the future, and in such case any applicable fees will be displayed prior to the User incurring such fee. Notwithstanding, the LULU Blockchain may have Blockchain Transaction Fees required to transact NFT or digital reward transactions through the LULU Blockchain. LULU may attempt to calculate for the User any Blockchain Transactions Fees, though such calculation may be inaccurate or excessive. The User may select a greater or lesser fee, and the User is solely responsible for paying any Blockchain Transaction Fees required on the LULU Blockchain. LULU will neither advance nor fund any Blockchain Transaction Fee on any User’s behalf, nor be responsible for any excess or insufficient fee calculation.

  1.5.8.  From time to time, there may be programs in place to allow User to receive a reward, in the form of LULU Reward, NFT, or otherwise, based on actions taken by the User, whether it be by referral or other program in place at the time (“Additional Rewards”).  User understands that LULU makes no representations or warrants regarding the Additional Rewards.  Notwithstanding or limiting the foregoing, LULU further makes no representations or warrants surrounding the operation of any LULU Services or that said LULU Services/Additional Rewards will be error-free or uninterrupted.  User accepts the sole responsibility for taking any and all actions to obtain any Additional Rewards, and holds LULU harmless for any opportunity cost or losses that occur as a result of the non-receipt of anticipated Additional Rewards, monetary or otherwise.

  1.6  LULU LAUNCHER

  The User understands and acknowledges that by downloading the application entitled “LULU Launcher” that it has read and understood and agrees to be bound to the Limited Software Warranty and License Agreement.

  2. PAYMENT TERMS.

  2.1. Annual License and Monthly Service Fees.

  The User shall pay a one-time LULU Game Node license fee. LULU or any of its affiliates or third parties may be the party that sells the software or hardware for any LULU Game Node.

  2.2. Software License.

  The User may be required to enter into a software license agreement with LULU or any third party for the use of any required software for each LULU Game Node. The User shall pay all associated software license fees.

  2.3. Equipment Purchase.

  The User may enter into an equipment purchase agreement as it relates to the purchase of any hardware for an LULU Game Node. The User is not required to purchase such hardware, but may use any equipment technology (e.g. computer, GPU, cell phone, or other technology) that can appropriately and safely access and connect to the LULU Blockchain.

  2.4. Maintenance and Hosting Fees.

  LULU does not maintain or host any LULU Game Node, but may refer the User to one or more third-party hosting companies that may or may not be affiliated with LULU. If the User elects and is part of a separate hosting agreement, the User may be required to pay certain data center operations, maintenance and power fees (“Maintenance Fees”).

  2.5. Blockchain Transaction Fees.

  The delivery and receipt of any of the User’s NFT or digital rewards through the LULU App may be subject to network or transaction fees charged by the blockchain associated with the User-selected algorithm (“Blockchain Transaction Fees”), which are non-refundable. Blockchain Transaction Fees are paid to emit, record, verify, and process a transaction on the blockchain. Any withdrawal or transfer of the User’s NFT or digital reward are subject to Blockchain Transaction Fees.

  2.6. Other Third-Party Fees.

  Certain digital apps, app addresses, tools, and third-party software and devices (“Third-Party Fees”) used by the User may also charge the User a fee, including a per transaction or transfer fee, which are non-refundable. The User is responsible for satisfying any such fee(s). The User should note that any such fees may significantly reduce the User’s rewards and therefore the User is responsible for managing the selection, use, rate and frequency of their receipt of rewards to any such Third-Party Fees.

  2.7. Taxes.

  The User is responsible for any taxes, and the User will pay for LULU Services without any reduction for taxes. If the User is required by law to withhold any taxes from its payments to LULU, the User must provide LULU with an official tax receipt or other qualified documentation to support such withholding, including value added tax (“VAT”), if applicable. The User will be liable to pay (or reimburse LULU) for any taxes, interest, penalties or fines which may arise from any mis-declaration made by the User. The User shall pay LULU for all taxes and governmental fees LULU is required to collect or pay upon sale or delivery of LULU Services.

  POTENTIAL USERS OF NFTS OR DIGITAL REWARDS, INCLUDING BUT NOT LIMITED TO BITCOIN, ARE FOREWARNED OF POSSIBLE FINANCIAL LOSS AT THE TIME SUCH REWARDS ARE EXCHANGED FOR FIAT CURRENCY DUE TO AN UNFAVORABLE EXCHANGE RATE. MOREOVER, A FAVORABLE EXCHANGE RATE AT THE TIME OF EXCHANGE MAY RESULT IN A TAX LIABILITY. USERS SHOULD CONSULT A TAX ADVISOR REGARDING ANY TAX CONSEQUENCES ASSOCIATED WITH THE PURCHASE, SALE, TRADE, RECEIPT OR OTHER USE OF DIGITAL REWARDS.

  3. USER OBLIGATIONS

  3.1. Software and Equipment Allocation.

  The User is responsible for the allocation of the User’s software and equipment and selected optimization decisions. The User acknowledges that LULU is not responsible for the selection or timing of blockchain protocols, nor is LULU responsible for the protocols selected for use in connection with LULU Services. The User is solely responsible for these decisions and shall monitor and allocate strategies through the User’s LULU App. The User acknowledges that the node transactions on any blockchain may vary and will not be uniform across each LULU Game Node.

  3.2. Log-in Credentials.

  The User represents and warrants that the User is responsible for the preservation of confidentiality of the User’s login credentials on the LULU App and any other login for the LULU Services. Login credentials generated for the User by LULU are for the User’s internal use only and the User is strictly prohibited from selling, transferring, or sub-licensing them to any other entity or person.

  3.3. Blockchain Network Risk.

  The User represents and warrants that the User accepts the risks of blockchain protocol and network, including instability, congestion, high transaction costs, network latency, information security, regulatory risk, and technological and operational error. The User understands these risks may result in delay or failure to process transactions and potentially high Blockchain Transaction Fees or Third Party Fees. The User represents and agrees that LULU is not responsible for any diminished LULU Services, related features, or capabilities resulting from blockchain network risk. In the event of a material increase or decrease to Blockchain Transaction Fees, Third Party Fees, or operational degradation, congestion, failure or other disruption of the blockchain network used by the User, LULU may, at its sole discretion and upon notice to the User, make any adjustments to the LULU Services.

  3.4. Blockchain Modification Risk.

  The User represents and warrants that the User is familiar with and accepts the risks associated with blockchain development and code changes. Blockchain technologies are still under development and may undergo significant changes over time. Blockchain contributors may make changes to features and specifications of the algorithm selected by the User, and may fork the LULU Blockchain protocol. Such changes may include or result in the elimination or support for specific algorithms and applications.

  3.5. Trade Compliance.

  User shall comply with all applicable import, re-import, sanctions, anti-boycott, export, and re-export control laws and regulations, including all such laws and regulations that apply to European Union and U.S. companies, such as the Export Administration Regulations, the International Traffic in Arms Regulations, and economic sanctions programs implemented by the Office of Foreign Assets Control and the European Union’s Common Foreign and Security Policy (collectively, “Trade Sanctions Laws”). The User represents and warrants that the User and the User’s financial institutions, or any party that owns or controls the User or the User’s financial institutions, are not subject to sanctions or otherwise designated on any list of prohibited or restricted parties, including but not limited to the lists maintained by the United Nations Security Council, the U.S. Government (e.g., the Specially Designated Nationals List and Foreign as Evaders List of the U.S. Department of Treasury, and the Entity List of the U.S. Department of Commerce), the European Union or its Member States, or other applicable government authority.

  3.6 Ownership Restrictions.

  User acknowledges and agrees that LULU, any game developer, or third party contact provider (or, as applicable, any licensors) own all legal right, title and interest in and to all elements of their respective intellectual property rights therein. The visual interfaces, graphics (including, without limitation, all art and drawings associated with the), design, systems, methods, information, computer code, software, services, “look and feel”, organization, compilation of the content, code, data, and all other elements of any content provided on the Site, LULU App, or LULU Blockchain are protected by copyright, trade dress, patent, and trademark laws, international conventions, other relevant intellectual property and proprietary rights, and applicable laws. All such intellectual property are the property of its owners or licensors, and all trademarks, service marks, and trade names are proprietary to its owner or licensors. Except as expressly set forth herein, the use of the LULU Services and LULU App does not grant User any ownership of or any other rights with respect to any content, code, data, or other materials that you may access on or through the LULU App.  Notwithstanding the foregoing, when a User purchases or owns a Platform Asset, the User owns the underlying NFT completely for as long as the User owns the Platform Asset. Ownership of the NFT is mediated entirely by the smart contract and Ethereum Network (or any other applicable network): at no point may LULU seize, freeze, or otherwise modify the ownership of the Platform Asset.  Subject to the continued compliance with the terms and conditions (only where the Platform has the right to offer same AND for only as long as the User still owns the Platform Asset), the User is granted with a worldwide, non-exclusive, non-transferable, royalty-free license to use and display the art underlying the Platform Asset solely for the following purposes: (1) for the User’s personal, non-commercial use; (2) as a part of the Platform Auction that allows for the purchase and sale of Platform Assets or on the Platform itself (if applicable), or; (3) as the party of a third-party marketplace or application that allows the User to transfer its User’s Platform Asset and permits the inclusion, involvement, or participation of the Platform Asset.

  3.7 Children.

  USER AFFIRMS HE/SHE IS OVER THE AGE OF 13, AS THE LULU APP AND LULU SERVICES ARE NOT INTENDED FOR CHILDREN UNDER AGE 13. IF YOU ARE 13 OR OLDER BUT UNDER THE AGE OF 18, OR THE LEGAL AGE OF MAJORITY WHERE YOU RESIDE IF THAT JURISDICTION HAS AN OLDER AGE OF MAJORITY, THEN USER AGREES TO REVIEW THESE TERMS WITH YOUR PARENT OR GUARDIAN TO MAKE SURE THAT BOTH USER AND YOUR PARENT OR GUARDIAN UNDERSTAND AND AGREE TO THESE TERMS. USER AGREES TO HAVE YOUR PARENT OR GUARDIAN REVIEW AND ACCEPT THESE TERMS ON YOUR BEHALF. IF YOU ARE A PARENT OR GUARDIAN AGREEING TO THE TERMS FOR THE BENEFIT OF A CHILD OVER 13, THEN YOU AGREE TO AND ACCEPT FULL RESPONSIBILITY FOR THAT CHILD’S USE OF THE LULU APP AND LULU SERVICES, INCLUDING ALL FINANCIAL CHARGES AND LEGAL LIABILITY THAT HE OR SHE MAY INCUR.

  3.8 Responsibility for Conduct.

  User takes responsibility for all activities that occur under its LULU App and for its use of the LULU Services, and User accepts all risks of any authorized or unauthorized access to its LULU App, to the maximum extent permitted by law. User represents and warrants that the User is familiar with and accepts the risks associated with digital Apps and private keys, including the risks described herein. User is solely responsible for its own conduct while accessing or using the LULU Services or LULU App, and for any consequences thereof. User agrees to use the LULU Services, LULU App, and LULU Blockchain for purposes that are legal, proper and in accordance with these Terms and any applicable laws or regulations. By way of example, and not as a limitation, User may not, and may not allow any third party to: (i) send, upload, distribute or disseminate any unlawful, defamatory, harassing, abusive, fraudulent, obscene, or otherwise objectionable content; (ii) distribute viruses, worms, defects, Trojan horses, corrupted files, hoaxes, or any other items of a destructive or deceptive nature; (iii) impersonate another person (via the use of an email address or otherwise); (iv) upload, post, transmit or otherwise make available through the LULU Services any content that infringes the intellectual proprietary rights of any party; (v) use the LULU Services to violate the legal rights (such as rights of privacy and publicity) of others; (vi) engage in, promote, or encourage illegal activity (including, without limitation, money laundering); (vii) interfere with other users’ enjoyment of the LULU App or LULU Blockchain; (viii) exploit the LULU Services for any unauthorized commercial purpose; (ix) modify, adapt, translate, or reverse engineer any portion of the LULU Services; (x) remove any copyright, trademark or other proprietary rights notices contained in or on the LULU App or LULU Blockchain or any part of it; (xi) reformat or frame any portion of the LULU App; (xii) display any content on the LULU App or LULU Blockchain that contains any hate-related or violent content or contains any other material, products or services that violate or encourage conduct that would violate any criminal laws, any other applicable laws, or any third party rights; (xiii) use any robot, spider, site search/retrieval application, or other device to retrieve or index any portion of the LULU App or the content posted on the LULU App, or to collect information about its users for any unauthorized purpose; (xiv) create user accounts by automated means or under false or fraudulent pretenses; (xv) trick, defraud, or mislead LULU or Users, with specific to an attempt to learn sensitive account information; (xvi) attempt to impersonate another User; (xvii) attempt to bypass any security measure of the Site; (xvii) copy or adapt the Site; or, (xviii) disparage, tarnish, or otherwise harm, in LULU’s sole discretion, LULU and/or the Site.

  3.9 Representations Made By User.

  User acknowledges and agrees that the LULU Services, including but not limited to the LULU Game Node and LULU Reward, ARE NOT being sold as an investment by or of LULU.  THE USER UNDERSTANDS THAT ANY REPRESENTATIONS MADE BY THE USER AT ANY TIME THAT ANY OF THE LULU SERVICES ARE AN INVESTMENT IN LULU (OR OTHERWISE, INCLUDING, BUT NOT LIMITED TO, IN GENERAL) TO OTHERS IN A DIRECT ATTEMPT TO MARKET LULU SERVICES IN COORDINATION WITH SUPPLYING USER’S REFERRAL LINK IS A DIRECT BREACH OF THE TERMS & CONDITIONS. A determination of same will be made at the sole discretion of LULU.

  3.10  LULU GAME NODE REPRESENTATIONS

  LULU and the User recognize that the SOLE AND ONLY purpose of the LULU Game Node is to support the LULU Games Node Ecosystem.  Nothing contained in this Agreement, exhibit to this Agreement, or any representation made outside of this Agreement, conveys on the User any ownership interests in LULU or its subsidiaries, or interests otherwise in the LULU (including, but not limited to voting rights in the LULU), nor any expectation of profits from the efforts of the LULU or its principals or subsidiaries.  The User understands that while it may from time to time receive rewards in line with the distribution schedule of the Node Ecosystem (“Distribution Rewards'') (subject to change), said reward is solely earned because of and as a direct result of work accomplished and performed by the User (i.e. work done by the LULU Game Node).  The User recognizes that should the User never actually run the LULU Game Node, it will receive no rewards.  LULU has no control of the method in which rewards are distributed to the LULU Game Node.  It is anticipated that the LULU Game Node will be able to be sold or transferred in the future as Non-Fungible Tokens, however, LULU cannot and does not warrant or represent that the resale value of the Nodes will be higher than the purchase price should this event occur, nor that it will be legally possible to do so.  Further, LULU cannot and does not warrant or represent that there will ever be a resale value or capability of the LULU Game Node.  

  3.11  Play to Earn Mechanisms

  If the User elects to engage in any play to earn mechanism (including, but not limited to, any mechanism that permits the User to play any games or use any LULU Services on the LULU App, Site or otherwise), the User will be responsible to pay any and all sales, use, value-added or other taxes, duties and assessments now or hereinafter claimed or imposed by any governmental authority.  The User will reimburse LULU for all national, federal, state, local, or other taxes and assessments of any jurisdiction, including value-added taxes and taxes as required by international tax treaties, customs or other import or export taxes, and amounts levied in lieu thereof based on charges set, services performed or payments made hereunder, as are now or hereafter may be imposed under the authority of any national, state, local or any other taxing jurisdiction; and (ii) shall not be entitled to deduct the amount of any such taxes, duties or assessments from payments made to us pursuant to these Terms.  User is solely responsible for determining what, if any, taxes apply to User and play to earn mechanisms, and any other transactions conducted by the User.  LULU does not act as a withholding tax agent in any circumstances.

  User further understands and acknowledges that LULU is not responsible, and User accepts sole responsibility for any and all missed LULU Reward or otherwise, regardless of the source of any error, fault or otherwise.   Any and all play to earn mechanisms in place (including, but not limited to, the method, amounts or otherwise) are not permanent and may or may not be changed at the sole discretion of LULU at any time.  

  4. TERMINATION

  4.1. General.

  LULU may suspend or terminate the User’s right to access or use LULU Services immediately and without notice if: (i) LULU determines the User’s use of the LULU Services poses a security risk to LULU Services or any third party, could adversely impact LULU, LULU Services, LULU Blockchain or any other LULU users, or could subject LULU, its affiliates, or any third party to liability, or could be fraudulent; (ii) the User is in breach of these Terms & Conditions; (iii) the User initiated a chargeback or dispute with respect to any payment or purchase of the LULU Services; (iv) the User has ceased to operate in the ordinary course, made an assignment for the benefit of creditors or similar disposition assets, or become the subject of any bankruptcy, reorganization, liquidation, dissolution or similar proceeding; or (v) for any other reason at LULU’s discretion.

  4.2. Effect of Suspension.

  If LULU suspends the User’s right to access or use any portion or all of the LULU Services, the User shall remain responsible for all fees and charges the User incurs during the period of suspension, including any Maintenance Fees and Blockchain Transaction Fees; and the User may be in violation of the User’s hosting agreement or the blockchain protocols, which may prevent or limit the User’s entitlement or access to any results or rewards that may have occurred during the User’s suspension of the LULU Services. User agrees to pay any fee charged by LULU to reconnect the LULU Services.

  4.3. Effect of Termination.

  If LULU terminates the User’s right to access or use any portion or all of the LULU Services, then all of the User’s rights under these Terms & Conditions immediately terminate and the User shall remain responsible for all fees owed to LULU incurred through the termination date.

  5. GOVERNANCE

  5.1. Advisory Board. The LULU Blockchain may have an advisory board.

  5.2. Voting for LULU Blockchain Updates and Amendments. The LULU Blockchain may have voting protocols.

  5.3. Consensus Nodes. The LULU Blockchain may have consensus nodes, which are the LULU Game Nodes that approve and validate transactions, and contribute to the security and stability of the network. Any User that owns an LULU Game Node involved in the consensus protocol may be rewarded from the LULU Blockchain and be able to charge Blockchain Transaction Fees.

  5.4. Community and Decentralized Innovation. The LULU Blockchain invites any person or entity throughout the world to contribute to the LULU Blockchain, including coders, application developers, marketers, advertisers, and service and maintenance providers. Accepted amendments, updates, and innovation from individuals or groups of the LULU Blockchain community may be rewarded from the LULU Blockchain rewards.

  6. PUBLICITY

  The User is permitted to state publicly that it is a customer or user of LULU, consistent with any Trademark Guidelines which may be adopted by LULU from time to time. The User agrees to abide by the Privacy Policy and Code of Conduct of LULU.

  7. REPRESENTATIONS AND WARRANTIES

  Each party represents and warrants that: (i) it has full power and authority to enter into these Terms & Conditions; and (ii) it will comply with all laws and regulations applicable to its provision or use of LULU Services. USER ACKNOWLEDGES AND AGREES THAT USER DOES NOT RESIDE IN ANY REGION THAT EXPLICITLY BANS THE USE OF LOOT BOXES IN GAMES IN ACCORDANCE WITH GAMBLING LAWS.

  8. DISCLOSURES & RISKS

  8.1 Notification. LULU notifies each User of certain disclosures and risks associated with blockchain NFT and digital rewards and their associated technology and protocols. LULU Services are not an investment product, and no action, notice, communication by any means, or omission by LULU shall be understood or interpreted as such. LULU has no influence whatsoever on the LULU Blockchain, the transactions and consensus protocols, or the NFTs or digital rewards, including the LULU Reward. Ownership of a LULU App or Game Node or the use of LULU Services does not represent or constitute any ownership right or stake, share or security, debt or equivalent right, or any right to receive any future revenue or form of participation in or relating to any blockchain or digital reward, including the LULU Blockchain or LULU Reward.

  8.2 Digital Rewards. Digital rewards are not considered legal tender, are not issued or backed by any government, and have fewer regulatory protections than traditional currency. Moreover, digital rewards are not insured against theft or loss by any insurance corporation or any investor protection, including the Federal Deposit Insurance Corporation or the Securities Investor Protection Corporation.

  8.3 Market Risk. The value of NFTs and digital rewards are derived from supply and demand in the global marketplace, which can rise or fall independent of any government currency. Holding NFTs and digital rewards carries exchange rate and other types of risk. The value of NFTs and digital rewards may be derived from the continued willingness of market participants to exchange traditional government currency for digital rewards, which may result in the potential for permanent and total loss of value of a particular digital reward should the market disappear. The volatility and unpredictability of the price and value of NFTs and digital rewards, relative to government currency, may result in significant loss over a short period of time. LULU cannot guarantee or warrant the value of any NFT, digital reward or blockchain, including the LULU Blockchain and LULU Reward, and explicitly warns the User that that there is no reason to believe that any NFT or blockchain reward will increase in value, and that they may hold no value, decrease in value, or entirely lose value.

  8.4. Regulatory Risk. Legislative and regulatory changes or actions at the state, federal, or international level may adversely affect the use, transfer, exchange, and value of virtual NFTs and blockchain rewards.  The regulatory status of cryptographic tokens, digital assets and blockchain technology is unclear or unsettled in many jurisdictions. It is difficult to predict how or whether governmental authorities will regulate such technologies. It is likewise difficult to predict how or whether any governmental authority may make changes to existing laws, regulations and/or rules that will affect cryptographic tokens, digital assets, blockchain technology and its applications.  Such changes could negatively impact the LULU Services in various ways, including, for example, through a determination that any of the above are regulated financial instruments that require registration. LULU may cease any distribution of any of the above, the development of the LULU Games platform or cease operations in a jurisdiction in the event that governmental actions make it unlawful or commercially undesirable to continue to do so.  The industry in which LULU operates is new, and may be subject to heightened oversight and scrutiny, including investigations or enforcement actions. There can be no assurance that governmental, quasi-governmental, regulatory or other similar types of (including banking) authorities will not examine the operations of LULU and/or pursue enforcement actions against LULU. Such governmental activities may or may not be the result of targeting LULU in particular. All of this may subject LULU to judgments, settlements, fines or penalties, or cause LULU to restructure its operations and activities or to cease offering certain products or services, all of which could harm LULU’s reputation or lead to higher operational costs, which may in turn have a material adverse effect on the LULU Services.

  8.5 Technology Risk. Virtual NFT and digital reward transactions may be irreversible and losses due to fraudulent or accidental transactions may not be recoverable. Some virtual transactions are deemed to be made when recorded on a public ledger, which may not necessarily be the date or time the user initiated the transaction. The nature of such virtual transactions may lead to an increased risk of fraud or cyber-attacks.

  8.6 Changes to LULU Game Node Network.  

  LULU and User recognize that from time to time amendments will be made to the LULU Game Node Network.  LULU and User both specifically agree that LULU will, from time to time, present the LULU Game Node Network with proposed amendments (the “Proposed Amendments'') that the Node Network will then vote on whether to implement or not (the “Governance Vote”).  The User understands that the Proposed Amendments will be made at the discretion of LULU, and LULU owes the User no duty or obligation to make proposals in its best interests.  The User specifically understands that there may come a time when LULU proposes an amendment that is not in or in direct opposition to the User’s best interests, financial or otherwise (including, but not limited to a change in the distribution calculation), and the User has no legal recourse against LULU should any Proposed Amendment be approved and implemented through the Governance Vote.  The User’s only recourse is to vote against said Proposed Amendment.  LULU and the User both agree that one such Proposed Amendment may be to change the specifications, including, but not limited to the internet connection, Random Access Memory, Central Processing Unit requirements, extra space, and any other requirements needed to run the Nodes (the “Specifications”).  LULU and User further agree that while the Specifications may be minimal on the effective date of this Agreement, this is subject to change through the Proposed Amendment and the Governance Vote.  While LULU does represent and covenant that the LULU Game Node will always be able to be run using the current specifications, LULU does not and cannot represent or covenant that any rewards earned (financial or otherwise) for doing so are not subject to change.  

  9. DISCLAIMER

  EXCEPT AS EXPRESSLY PROVIDED FOR IN THESE TERMS & CONDITIONS, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LULU, ITS AFFILIATES, AND ITS SUPPLIERS DO NOT MAKE ANY OTHER WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR USE AND NON-INFRINGEMENT. LULU, ITS AFFILIATES, AND ITS SUPPLIERS ARE NOT RESPONSIBLE OR LIABLE FOR THE DELETION, FAILURE TO STORE, OR ANY LOSS OF ANY USER DATA, INCLUDING BLOCKCHAIN DATA, NFT AND DIGITAL REWARDS DERIVED, MAINTAINED, OR TRANSMITTED THROUGH USE OF LULU SERVICES. THE USER IS SOLELY RESPONSIBLE FOR SECURING ITS CUSTOMER DATA AND DIGITAL REWARDS. NEITHER LULU, ITS AFFILIATES, NOR ITS SUPPLIERS, WARRANTS THAT THE OPERATION OF LULU SERVICES, LULU BLOCKCHAIN, OR ANY OTHER SUPPORTED BLOCKCHAIN WILL BE ERROR-FREE OR UNINTERRUPTED. LULU, ITS AFFILIATES, AND ITS SUPPLIERS ARE NOT RESPONSIBLE OR LIABLE FOR ANY LOSSES OR OPPORTUNITY COSTS RESULTING FROM BLOCKCHAIN NETWORK AND PROTOCOL OR THIRD-PARTY SOFTWARE ISSUES, WHICH MAY IN TURN RESULT IN THE INABILITY TO PROCESS TRANSACTIONS ON ANY BLOCKCHAIN AT ALL OR WITHOUT INCURRING SUBSTANTIAL FEES.

  10. LIMITATION OF LIABILITY

  10.1. Limitation of Indirect Liability.

  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LULU AND THE USER SHALL NOT BE LIABLE UNDER THESE TERMS & CONDITIONS FOR LOST REVENUES, OPPORTUNITY COSTS, OR INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, EVEN IF LULU KNEW OR SHOULD HAVE KNOWN THAT SUCH DAMAGES WERE POSSIBLE AND EVEN IF DIRECT DAMAGES DO NOT SATISFY A REMEDY. THIS LIMITATION OF LIABILITY DOES NOT APPLY TO VIOLATIONS OF LULU’S INTELLECTUAL PROPERTY RIGHTS, INDEMNIFICATION OBLIGATIONS, OR THE USER’S PAYMENT OBLIGATIONS.

  10.2. Limitation of Amount of Liability.

  TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEITHER LULU NOR ITS AFFILIATES OR SUPPLIERS, MAY BE HELD LIABLE UNDER THESE TERMS & CONDITIONS FOR MORE THAN THE AMOUNT PAID BY THE USER TO LULU UNDER THESE TERMS & CONDITIONS FOR THE 12 MONTH PERIOD PRECEDING THE DATE THE CLAIM AROSE, MINUS ANY REWARDS GENERATED OR RECEIVED BY THE USER AS A RESULT OF THE USE OF LULU SERVICES.

  11. INDEMNIFICATION

  Unless prohibited by applicable law, the User will defend and indemnify LULU and its Affiliates against any settlement amounts approved by the User and damages and costs finally awarded against the User and its affiliates by a court of competent jurisdiction in any formal legal proceeding filed by an unaffiliated third party before a court or government tribunal (including any appellate proceeding) to the extent arising from the User’s use of LULU Services.

  12. MISCELLANEOUS.

  12.1. Assignment.

  The User will not assign or otherwise transfer the User’s rights and obligations under these Terms & Conditions, without the prior written consent of LULU, which may be unreasonably withheld. Any assignment or transfer in violation of this section will be void. At any time and without the need for User’s consent, LULU may assign any obligation, right and these Terms & Conditions. Subject to the foregoing, these Terms & Conditions will be binding upon, and inure to the benefit of the parties and their respective permitted successors and assigns. The User may not merge these Terms & Conditions with any other agreements with which LULU may be a party.

  12.2. Disputes.

  Any dispute, controversy, difference or claim arising out of or relating to these Terms & Conditions or relating in any way to the User’s use of LULU sites or LULU Services, including the existence, validity, interpretation, performance, breach or termination thereof or any dispute regarding non-contractual obligations arising out of or relating to these Terms & Conditions the parties may agree to first attempt mediation before a single mediator, administered by the International Centre for Dispute Resolution under its mediation rules, to be held in any location agreed to by the parties, or Salt Lake City, Utah, USA in the English language. If the parties do not agree on mediation, the matter shall be referred to and finally resolved by arbitration before a single arbitrator to be held in Salt Lake City, Utah, USA administered by the International Centre for Dispute Resolution in accordance with International Dispute Resolution Rules. The decision of the arbitrator is final and binding on the parties, and enforceable in a court of competent jurisdiction. The prevailing party shall be entitled to costs and reasonable attorneys’ fees for the arbitration. Notwithstanding the foregoing LULU and the User agree that LULU may bring suit in any court of law to enjoin infringement or other misuse of LULU’s intellectual property rights. Any disputes that may arise beyond the scope of the arbitration provision shall be exclusively subject to the State or Federal Courts located in Salt Lake City, Utah, USA. The User and LULU consent to personal jurisdiction in those courts. CLASS ACTION WAIVER: TO THE EXTENT PERMISSIBLE BY LAW, ALL CLAIMS MUST BE BROUGHT IN A PARTY’S INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE ACTION, OR REPRESENTATIVE PROCEEDING (COLLECTIVELY “CLASS ACTION WAIVER”). THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON’S CLAIMS OR ENGAGE IN ANY CLASS ARBITRATION. USER ACKNOWLEDGES THAT, BY AGREEING TO THESE TERMS, EACH PARTY WAIVES THE RIGHT TO A TRIAL BY JURY AND THE RIGHT TO PARTICIPATE IN A CLASS ACTION.

  12.3. Entire Agreement.

  These Terms & Conditions sets out all the terms agreed between the parties and supersedes all other agreements between the parties relating to its subject matter. In entering into these Terms & Conditions, neither party has relied on, and neither party will have any right or remedy based on, any statement, representation or warranty (whether made negligently or innocently), except those expressly set out in these Terms & Conditions. The terms may be updated on LULU sites.

  12.4. Force Majeure.

  LULU and its affiliates will not be liable for any failure or delay in performance of obligation under these Terms & Conditions where the failures or delay results from any cause beyond reasonable control, including, but not limited to, acts of God, labor disputes or other industrial disturbances, electrical or power outages, utilities or other telecommunications failures, earthquake, storms or other elements of nature, blockages, embargoes, riots, acts or orders of government, acts of terrorism, or war. Force Majeure events include, but are not limited to, upgrades to the validation rules of a given blockchain (e.g., a “hard fork” or “soft fork”).

  12.5. Governing Law.

  Any claim or dispute between the User and LULU arising out of or relating to the User’s use of LULU sites, LULU Services, or these Terms & Conditions, in whole or in part, shall be governed by the laws of the State of Wyoming, USA without respect to its conflict of laws provisions. The 1980 United Nations Conventions on Contracts for the International Sale of Goods does not govern these Terms & Conditions.

  12.6. Language.

  All communications and notices made or given pursuant to these Terms & Conditions must be in the English language. If we provide a translation of the English language version of these Terms & Conditions, the English language version will control if there is any conflict.

  12.7. Notices to the User and LULU.

  LULU may provide any notice to the User under these Terms & Conditions by: (i) posting a notice on LULU Site; or (ii) sending a message to the email address associated with the User’s account. Notices provided on LULU Site will be effective upon posting and notices provided by email will be effective when the email is sent. It is the User’s responsibility to keep the User’s email address current. To give LULU notice under these Terms & Conditions, the User must contact LULU by support@LULU.games. LULU may update the address for notices by posting on the LULU Site.

  12.8. Severability.

  If any portion of these Terms & Conditions is held to be invalid or unenforceable, the remaining portions will remain in full force and effect.
  `
}